### ISSUE TITLE
Why there are two redundants of body property?

### ISSUE THREAD

**Issue by alamenai** [MomenSherif/react-lib-boilerplate#1]
Source : [__normalize.scss](https://github.com/MomenSherif/react-lib-boilerplate/blob/main/src/_normalize.scss)
Line: [L21](https://github.com/MomenSherif/react-lib-boilerplate/blob/main/src/_normalize.scss#L22) , [L22](https://github.com/MomenSherif/react-lib-boilerplate/blob/main/src/_normalize.scss#L22).

**Comment by MomenSherif** [comment]
@MenaiAla Thanks for informing me about that ♥, actually its the normalize CSS reset file https://github.com/sindresorhus/modern-normalize, 
😅 and I didn't notice they are doing reset for font family and margin on body on two separate selectors, which is weird
